config/routes.rb
WEsource::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :resources
   root 'resources#index'

end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :user

	validates :title, presence: true
	validates :language, presence: true
	validates :link, presence: true
	  
end

app/models/user.rb
require "bcrypt"
class User < ActiveRecord::Base
	include BCrypt

	has_many :resources	

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :password_digest, presence: true
	validates :password_confirmation, presence: true
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

	has_secure_password

	validates_length_of :password_digest, minimum: 6
	validates_length_of :password_confirmation, minimum: 6
	validates_uniqueness_of :email
	validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create
	
	def password
  		@password
    end

	def password=(new_password)
	  	 @password = new_password
	    self.password_digest = BCrypt::Password.create(new_password)
	end

	def authenticate(test_password)
	    if BCrypt::Password.new(self.password_digest) == test_password
	      self
	    else
	      false
	    end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/resource_controller.rb
class ResourceController < ApplicationController
before_action :set_resource, :only => [:show, :edit, :update, :destroy]
respond_to :json, :html

	def index
		@resources = Resource.all
		respond_with @resources
	end

	def new
		@resource = Resource.new
	end

	def show
		respond_with @resource
	end

	def create
		@resource = Resource.new(resource_params)
		
		if @resource.save
			flash[:success] = "Your WEsource has been created!"
			respond_to do |format|
	        format.html { redirect_to resources_path }
	        format.json { render json: @resource, status: :created }
	      end
	    else
	      respond_to do |format|
	        format.html { render 'new' }
	        format.json { render json: @resource.errors, status: :unprocessable_entity }
	      end
		end
	end

	def edit
	end

	def update
	if @resource.update(resource_params)
	      respond_to do |format|
	        format.html { redirect_to resources_path }
	        format.json { render nothing: true, status: :no_content }
	      end
	    else
	      respond_to do |format|
	        format.html { render 'edit' }
	        format.json { render json: @resource.errors, status: :unprocessable_entity }
	      end
	    end
	end

	def destroy
		@resource.destroy

		respond_to do |format|
			format.html { redirect_to resources_path }
			format.json { render json: { head: :ok } }
		end
	end
	
	protected

	def set_resource
		@resource = resource.find(params[:id])
	end

	def resource_params
		params.require(:resource).permit(:title, :language, :link, :note)
	end

end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
before_action :set_resource, :only => [:show, :edit, :update, :destroy]
respond_to :json, :html

	def index
		@resources = Resource.all
		respond_with @resources
	end

	def new
		@resource = Resource.new
	end

	def show
		respond_with @resource
	end

	def create
		@resource = Resource.new(resource_params)
		if @resource.save
			respond_to do |format|
			format.html { redirect_to resources_path }
			format.json { render json: @resource, status: :created }
			end
	    else
	    	respond_to do |format|
	      	format.html { render 'new' }
       		format.json { render json: @resource.errors, status: :unprocessable_entity }
    		end
		end
	end

	def edit
	end

	def update
		if @resource.update(resource_params)
	      	respond_to do |format|
		        format.html { redirect_to resources_path }
		        format.json { render nothing: true, status: :no_content }
	      	end
	    else
	      	respond_to do |format|
		        format.html { render 'edit' }
		        format.json { render json: @resource.errors, status: :unprocessable_entity }
	      	end
		end
	end

	def destroy
		@resource.destroy

		respond_to do |format|
			format.html { redirect_to resources_path }
			format.json { render json: { head: :ok } }
		end
	end
	
	protected

	def set_resource
		@resource = Resource.find(params[:id])
	end

	def resource_params
		params.require(:resource).permit(:user_id, :created_at, :title, :language, :link, :note)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.where(:email => params[:session][:email]).first

    if @user && @user.authenticate(params[:session][:password])
      session[:remember_token] = @user.id
      @current_user = @user
      redirect_to root_path
    else
      flash[:error] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    session.delete(:remember_token)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Thank you for signing up!"
      session[:remember_token] = @user.id
      redirect_to root_path
    else
      raise @user.errors.inspect	
      render 'new'
    end
  end

  protected
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
    	if session[:remember_token]
    		@current_user ||= User.find(session[:remember_token])
        	puts @current_user
        	return @current_user
    	else
    		false
    	end
  	end

  	def authenticate_user
	    if !self.current_user
	      redirect_to new_session_path
	    end
  	end	
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Wesource" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>
    <%= favicon_link_tag 'wesource_diamond.png' %>
</head>
<body>
    <nav class="top-bar" data-topbar>
        <ul class="title-area">
            <li class="name">
                    <%= link_to resources_path do %> 
                        <%= image_tag "wesource_logo.png", id: "wesource_logo" %> 
                    <% end %>
            </li>
             <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
            <li class="toggle-topbar menu-icon">
                <a href="#"><span><!-- Menu --></span></a>
            </li>
        </ul>
        <section class="top-bar-section">
        <!-- Right Nav Section -->
            <ul class="right">
                <!-- <li class="active"><a href="#">Right Button Active</a></li> -->
                <li class="has-dropdown">
                    <a href="#"><%= image_tag "wesource_menu2.png", id: "wesource_menu" %></a>
                    <ul class="dropdown">
                        <% if !current_user %>
                            <li><%= link_to "Sign Up", new_user_path, id: "sign_up" %></li>
                            <li><%= link_to "Sign In", new_session_path, id: "sign_up" %></li>
                        <% end %>
                        <% if current_user %>
                            <li>
                                <a id="hello_user">Hello <%= current_user.first_name %>!</a>
                            </li>
                            <li>
                                <%= link_to "Sign Out", session_path(current_user), method: 'delete' %>
                            </li>
                        <% end %>
                    </ul>
                </li>
            </ul>
        <!-- Left Nav Section -->
        <!-- <ul class="left">
          <li><a href="#">Left Nav Button</a></li>
        </ul> -->
        </section>
    </nav>
    <div class="container-fluid">
        <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
    </div>
    <%= yield %>
    <%= javascript_include_tag "application" %>
</body>
</html>

app/views/resources/_form.html.erb
<h1 >Create a WEsource</h1>

<%= form_for Resource.new, :class=> "form-group" do |f| %>
    <%= f.text_field :title, :placeholder => "Title", :class => "form-control"  %>
    <%= f.text_field :language, :placeholder => "Language", :class => "form-control" %>
    <%= f.text_field :link, :placeholder => "Link", :class => "form-control" %>
    <%= f.text_area :note, :placeholder => "Note (optional)", :class => "form-control" %> <br/>
    <%= f.submit "Share", class: 'button success' %>
<% end %>

app/views/resources/index.html.erb
<div x-ng-app="resource-app" class="resources_index_container">
	
	<div x-ng-controller="ResourceCtrl">
		<div x-ng-show="errors" class="alert alert-danger alert-dismissable">
	        <button type="button" class="close" x-ng-click="clearErrors();" aria-hidden="true">&times;</button>
	      	<ul>
		        <li x-ng-repeat="(attribute, error) in errors">
		          {{attribute}} {{error.join(", ")}}
		        </li>
	        </ul>
	    </div>
	<% if !current_user %>    
	<div class="form-group small-12 columns search_container">
		<h3>Search For A Wesource</h3>
        <input x-ng-model="search" type="text" class="form-control search_bar" placeholder="Search Wesource">
    </div>
    <% end %>
    <% if current_user %>
    	<div class="form-group small-6 columns search_container">
			<h3>Search For A Wesource</h3>
	        <input x-ng-model="search" type="text" class="form-control search_bar" placeholder="Search Wesource">
    	</div>
	    <div class="wesource_form_container small-6 columns">
	    	<h3>Share New Wesource</h3>
		    <form x-ng-submit="saveResource();" class="form-group">
		      <input x-ng-model="newResource.title" name="title" class="form-control small-12 columns" placeholder="Title (Required)">
		      <input x-ng-model="newResource.language" name="language" class="form-control small-12 columns" placeholder="Language (Required)">
		      <input x-ng-model="newResource.link" name="link" class="form-control small-12 columns" placeholder="Link (Required)">
		      <input x-ng-model="newResource.note" name="note" class="form-control small-12 columns" placeholder="Notes (Optional)"> <br />
		      <input type="submit" value="SHARE" class="button tiny small-12 columns">
		    </form>
	    </div>
    <% end %>
    	<h1>Wesources</h1>
    	<div class="small-12 columns wesource_container ">
			<table id="resource_table" class="small-12">
				<thead>
					<tr class="table_headers">
						<th>Title</th>
						<th>Language</th>
						<th>Link</th>
						<th>Note</th>
					</tr>
				</thead>
				<tr x-ng-repeat="resource in resources | filter: searchWesource">
					<td> {{resource.title}} </td>
				 	<td> {{resource.language}} </td>
				 	<td id="link_container"> 
				 		<a href="{{resource.link}}" target="blank"><%= image_tag "wesource_diamond.png", id: "wesource_img" %></a> 
				 	</td>
				 	<td> {{resource.note}} </td>
				</tr>
			</table>	

		</div>
	</div>	
</div>

app/views/users/_form.html.erb
<div class="small-12 columns">
<h1>Create New User</h1>
	<%= form_for @user, :class=> "form-group" do |f| %>
		<%= f.text_field :first_name, :placeholder => "First Name", :class => "form-control" %>
		<%= f.text_field :last_name, :placeholder => "Last Name", :class => "form-control" %>	
		<%= f.text_field :email, :placeholder => "Email", :class => "form-control" %>
		<%= f.password_field :password, :placeholder => "Password (Minimum 6 Characters)", :class => "form-control" %>
		<%= f.password_field :password_confirmation, :placeholder => "Confirm Password", :class => "form-control" %> <br />
		<%= f.submit "Sign Up!", :class => "small-12 columns button success" %>
	<% end %>
</div>

app/views/users/new.html.erb
<%= render 'form' %>